name: Lint Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-commits:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v6
