name: Build with GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dummy upload artifact to avoid fetch error
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: README.md
          if-no-files-found: ignore

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload site content
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
